const data = {
  response_code: {
    version: '1.5',
    termsofService: 'http://frontend.turing.io/projects/family-feud.html',
    features: {
      surveys: 1,
      answers: 1
    },
  },
  surveys: [
    { id: 1, question: 'If You Drew Homer Simpson’s Name In A Secret Santa Exchange, What Would You Buy Him?' },
    { id: 2, question: 'Name Something You Do To An Item Before Giving It As A Gift' },
    { id: 3, question: 'Name A Good Gift For Someone Who Is Always Late.' },
    { id: 4, question: 'Why Might A Family Move Into A Bigger House?' },
    { id: 5, question: 'Other Than Movie Tickets, Name Something A Crowded Movie Theatre Might Run Out Of.' },
    { id: 6, question: 'Name Something You Should Probably Book Ahead Of Time If You’re Going On Vacation.' },
    { id: 7, question: 'Name A City Where You’d Hate The Long Commute To Work.' },
    { id: 8, question: 'What Might You Ask To Borrow From Someone At The Laundromat?' },
    { id: 9, question: 'On A Resume, What Might A Person Claim They Can Do Quickly?' },
    { id: 10, question: 'Name A Phrase That Often Appears In Children’s Stories' },
    { id: 11, question: 'Name Something That Can Be Pumped' },
    { id: 12, question: 'Other Than Illness, Name An Acceptable Excuse For Missing Work.' },
    { id: 13, question: 'Name A Crime That Some People Probably Commit Every Day.' },
    { id: 14, question: 'Name Something Tourists Point Up At' },
    { id: 15, question: 'Name Something You Might Add Milk To In The Morning.' }
  ],
  answers: [
    { answer: 'Alarm Clock', respondents: 34, surveyId: 3 },
    { answer: 'Beer', respondents: 67, surveyId: 1 },
    { answer: 'Bowling Ball', respondents: 5, surveyId: 1 },
    { answer: 'Buy It', respondents: 4, surveyId: 2 },
    { answer: 'Calendar', respondents: 3, surveyId: 3 },
    { answer: 'Can Afford More', respondents: 5, surveyId: 4 },
    { answer: 'Candy', respondents: 8, surveyId: 5 },
    { answer: 'Car', respondents: 3, surveyId: 6 },
    { answer: 'Car Trouble', respondents: 30, surveyId: 12 },
    { answer: 'Change', respondents: 24, surveyId: 8 },
    { answer: 'Chicago', respondents: 18, surveyId: 7 },
    { answer: 'Coffee', respondents: 17, surveyId: 15 },
    { answer: 'Cold Cereal', respondents: 67, surveyId: 15 },
    { answer: 'Detergent', respondents: 69, surveyId: 8 },
    { answer: 'Donuts', respondents: 24, surveyId: 1 },
    { answer: 'Dryer Sheets', respondents: 6, surveyId: 8 },
    { answer: 'Family Has Grown', respondents: 61, surveyId: 4 },
    { answer: 'Finish Tasks', respondents: 12, surveyId: 9 },
    { answer: 'Flight', respondents: 23, surveyId: 6 },
    { answer: 'Funeral', respondents: 61, surveyId: 12 },
    { answer: 'Gas', respondents: 58, surveyId: 11 },
    { answer: 'Happily Ever After', respondents: 9, surveyId: 10 },
    { answer: 'Hotel', respondents: 73, surveyId: 6 },
    { answer: 'Iron', respondents: 8, surveyId: 11 },
    { answer: 'Jaywalking', respondents: 18, surveyId: 13 },
    { answer: 'Jury Duty', respondents: 8, surveyId: 12 },
    { answer: 'Learn', respondents: 21, surveyId: 9 },
    { answer: 'Littering', respondents: 18, surveyId: 13 },
    { answer: 'Los Angeles', respondents: 21, surveyId: 7 },
    { answer: 'Mountains', respondents: 6, surveyId: 14 },
    { answer: 'New York City', respondents: 53, surveyId: 7 },
    { answer: 'Oatmeal', respondents: 3, surveyId: 15 },
    { answer: 'Once Upon A Time', respondents: 79, surveyId: 10 },
    { answer: 'Popcorn', respondents: 51, surveyId: 5 },
    { answer: 'Remove Price Tag', respondents: 27, surveyId: 2 },
    { answer: 'Space', respondents: 30, surveyId: 5 },
    { answer: 'Speeding', respondents: 62, surveyId: 13 },
    { answer: 'Statues / Monuments', respondents: 14, surveyId: 14 },
    { answer: 'Tall Buildings', respondents: 68, surveyId: 14 },
    { answer: 'The End', respondents: 10, surveyId: 10 },
    { answer: 'Tire', respondents: 24, surveyId: 11 },
    { answer: 'Type', respondents: 53, surveyId: 9 },
    { answer: 'Want More Space', respondents: 33, surveyId: 4 },
    { answer: 'Watch', respondents: 58, surveyId: 3 },
    { answer: 'Wrap It', respondents: 61, surveyId: 2 }
  ]
};

export default data;