const data = {
  response_code: {
    version: '1.2',
    termsofService: 'http://frontend.turing.io/projects/wheel-of-fortune.html',
    features: {
      wheel: 1,
      puzzles: 1
    },
  },
  wheel: [
    900,
    'BANKRUPT',
    2500,
    600,
    700,
    600,
    650,
    500,
    700,
    'BANKRUPT',
    600,
    550,
    500,
    600,
    'BANKRUPT',
    'LOSE A TURN',
    700,
    800,
    500,
    650,
    500,
    900
  ],
  puzzles: {
    one_word_answers: {
      date: 'Oct 07 2018',
      puzzle_bank: [
        {  
          category: 'Around The House',
          number_of_words: 1,
          total_number_of_letters: 8,
          first_word: 8, 
          description:'Location or object(s) found within a typical house.',
          correct_answer: 'Armchair',
        },
        {  
          category: 'The 90s',
          number_of_words: 1,
          total_number_of_letters: 7,
          first_word: 7, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Beepers',
        },
        {  
          category: 'The 90s',
          number_of_words: 1,
          total_number_of_letters: 10,
          first_word: 10, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Tamagotchi',
        },
        {  
          category: 'Around The House',
          number_of_words: 1,
          total_number_of_letters: 6,
          first_word: 6,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Teapot',
        },
        {  
          category: 'The 90s',
          number_of_words: 1,
          total_number_of_letters: 10,
          first_word: 10, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Scrunchies',
        },
        {  
          category: 'Around The House',
          number_of_words: 1,
          total_number_of_letters: 8,
          first_word: 8,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Mousepad',
        },
        {  
          category: 'The 90s',
          number_of_words: 1,
          total_number_of_letters: 9,
          first_word: 9, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Sketchers',
        },
        {  
          category: 'Around The House',
          number_of_words: 1,
          total_number_of_letters: 8,
          first_word: 8,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Toolkits',
        },
        {  
          category: 'Phrase',
          number_of_words: 1,
          total_number_of_letters: 7,
          first_word: 7, 
          description: 'any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Bonjour',
        },
         {  
          category: 'The 90s',
          number_of_words: 1,
          total_number_of_letters: 9,
          first_word: 9, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Operation',
        },
         {  
          category: 'The 90s',
          number_of_words: 1,
          total_number_of_letters: 3,
          first_word: 3, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Moo',
        },
        {  
          category: 'Phrase',
          number_of_words: 1,
          total_number_of_letters: 6,
          first_word: 6, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Cheers',
        },
        {  
          category: 'Phrase',
          number_of_words: 1,
          total_number_of_letters: 2,
          first_word: 2, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Hi',
        },
        {  
          category: 'Phrase',
          number_of_words: 1,
          total_number_of_letters: 10,
          first_word: 10, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Hocus-Pocus',
        },
        {  
          category: 'Phrase',
          number_of_words: 1,
          total_number_of_letters: 6,
          first_word: 6, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Presto',
        },
        {  
          category: 'Phrase',
          number_of_words: 1,
          total_number_of_letters: 12,
          first_word: 12,
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Trick-Or-Treat',
        },{  
          category:'Rhyme Time',
          number_of_words: 1,
          total_number_of_letters: 11,
          first_word: 11,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Tutti-Fruiti',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 1,
          total_number_of_letters: 10,
          first_word: 10,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Lovey-Dovey',
        },
        {  
          category: 'Around The House',
          number_of_words: 1,
          total_number_of_letters: 11,
          first_word: 11,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Windowpanes',
        },{  
          category:'Around The House',
          number_of_words: 1,
          total_number_of_letters: 10,
          first_word: 10,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Snowblower',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 1,
          total_number_of_letters: 7,
          first_word: 7,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Hotshot',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 1,
          total_number_of_letters: 10,
          first_word: 10,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Superduper',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 1,
          total_number_of_letters: 10,
          first_word: 10,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Willy-Nilly',
        },{  
          category:'Rhyme Time',
          number_of_words: 1,
          total_number_of_letters: 6,
          first_word: 6,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Bow-wow',
        }
      ]
    },
    two_word_answers: {
      date: 'Oct 07 2018',
      puzzle_bank: [
        {  
          category: 'Around The House',
          number_of_words: 2,
          total_number_of_letters: 11,
          first_word: 7, 
          description:'Location or object(s) found within a typical house.',
          correct_answer: 'Amusing Yarn',
        },
        {  
          category: 'The 90s',
          number_of_words: 2,
          total_number_of_letters: 11,
          first_word: 4, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Bowl Haircut',
        },
        {  
          category: 'The 90s',
          number_of_words: 2,
          total_number_of_letters: 13,
          first_word: 7, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Britney Spears',
        },
        {  
          category: 'Around The House',
          number_of_words: 1,
          total_number_of_letters: 12,
          first_word: 7,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Beanbag Chair',
        },
        {  
          category: 'The 90s',
          number_of_words: 2,
          total_number_of_letters: 9,
          first_word: 4, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Lite Brite',
        },
        {  
          category: 'Around The House',
          number_of_words: 2,
          total_number_of_letters: 8,
          first_word: 5,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Brass bed',
        },
        {  
          category: 'The 90s',
          number_of_words: 2,
          total_number_of_letters: 9,
          first_word: 5, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'South Park',
        },
        {  
          category: 'Around The House',
          number_of_words: 2,
          total_number_of_letters: 15,
          first_word: 4,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Chic Furnishings',
        },
        {  
          category: 'Phrase',
          number_of_words: 2,
          total_number_of_letters: 6,
          first_word: 4, 
          description: 'any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Fess Up',
        },
         {  
          category: 'The 90s',
          number_of_words: 2,
          total_number_of_letters: 6,
          first_word: 3, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Fun Dip',
        },
         {  
          category: 'The 90s',
          number_of_words: 2,
          total_number_of_letters: 10,
          first_word: 6, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Celine Dion',
        },
        {  
          category: 'Phrase',
          number_of_words: 2,
          total_number_of_letters: 7,
          first_word: 3, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Get Lost',
        },
        {  
          category: 'Phrase',
          number_of_words: 2,
          total_number_of_letters: 8,
          first_word: 5, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Admit One',
        },
        {  
          category: 'Phrase',
          number_of_words: 2,
          total_number_of_letters: 9,
          first_word: 3, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'You Betcha',
        },
        {  
          category: 'Phrase',
          number_of_words: 2,
          total_number_of_letters: 10,
          first_word: 4, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Open Sesame',
        },
        {  
          category: 'Phrase',
          number_of_words: 2,
          total_number_of_letters: 11,
          first_word: 4,
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Good Morning',
        },{  
          category: 'Around The House',
          number_of_words: 2,
          total_number_of_letters: 11,
          first_word: 11,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Windowpanes',
        },{  
          category:'Rhyme Time',
          number_of_words: 2,
          total_number_of_letters: 8,
          first_word: 4,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Wine & Dine',
        },{  
          category:'Rhyme Time',
          number_of_words: 2,
          total_number_of_letters: 10,
          first_word: 5,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Fight Night',
        },
        {  
          category:'Around The House',
          number_of_words: 2,
          total_number_of_letters: 9,
          first_word: 4,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Corn Syrup',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 2,
          total_number_of_letters: 11,
          first_word: 6,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Flower Power',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 2,
          total_number_of_letters: 15,
          first_word: 7,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Jeepers Creepers',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 2,
          total_number_of_letters: 10,
          first_word: 4,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Even Steven',
        },{  
          category:'Rhyme Time',
          number_of_words: 2,
          total_number_of_letters: 6,
          first_word: 3,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Fat Cat',
        }
      ]
    },
    three_word_answers: {
      date: 'Oct 07 2018',
      puzzle_bank: [
        {  
          category: 'Around The House',
          number_of_words: 3,
          total_number_of_letters: 10,
          first_word: 3, 
          description:'Location or object(s) found within a typical house.',
          correct_answer: 'Hot Glue Gun',
        },
        {  
          category: 'The 90s',
          number_of_words: 3,
          total_number_of_letters: 12,
          first_word: 6, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Tickle Me Elmo',
        },
        {  
          category: 'The 90s',
          number_of_words: 3,
          total_number_of_letters: 13,
          first_word: 2, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'In Living Color',
        },
        {  
          category: 'Around The House',
          number_of_words: 1,
          total_number_of_letters: 13,
          first_word: 5,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Detox Foot Pads',
        },
        {  
          category: 'The 90s',
          number_of_words: 3,
          total_number_of_letters: 19,
          first_word: 3, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'The Smashing Pumpkins',
        },
        {  
          category: 'Around The House',
          number_of_words: 3,
          total_number_of_letters: 14,
          first_word: 6,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Wooden End Table',
        },
        {  
          category: 'The 90s',
          number_of_words: 3,
          total_number_of_letters: 14,
          first_word: 5, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Magic School Bus',
        },
        {  
          category: 'Around The House',
          number_of_words: 3,
          total_number_of_letters: 15,
          first_word: 3,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'USB Power Adapter',
        },
        {  
          category: 'Phrase',
          number_of_words: 3,
          total_number_of_letters: 6,
          first_word: 1, 
          description: 'any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'I Dig It',
        },
          {  
          category: 'The 90s',
          number_of_words: 3,
          total_number_of_letters: 19,
          first_word: 4, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Best Friend Necklaces',
        },
          {  
          category: 'The 90s',
          number_of_words: 3,
          total_number_of_letters: 13,
          first_word: 3, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Air Jordan Sneakers',
        },
        {  
          category: 'Phrase',
          number_of_words: 3,
          total_number_of_letters: 8,
          first_word: 2, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'By The Way',
        },
        {  
          category: 'Phrase',
          number_of_words: 3,
          total_number_of_letters: 8,
          first_word: 5, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Admit One',
        },
        {  
          category: 'Phrase',
          number_of_words: 3,
          total_number_of_letters: 8,
          first_word: 3, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Get A Grip',
        },
        {  
          category: 'Phrase',
          number_of_words: 3,
          total_number_of_letters: 9,
          first_word: 4, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Cool As Ice',
        },
        {  
          category: 'Phrase',
          number_of_words: 3,
          total_number_of_letters: 10,
          first_word: 2,
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'No Such Luck',
        },{  
          category: 'Around The House',
          number_of_words: 3,
          total_number_of_letters: 16,
          first_word: 6,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'French Rolling Pin',
        },{  
          category:'Rhyme Time',
          number_of_words: 3,
          total_number_of_letters: 8,
          first_word: 4,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Hop On Pop',
        },{  
          category:'Rhyme Time',
          number_of_words: 3,
          total_number_of_letters: 11,
          first_word: 5,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Twice As Nice',
        },
        {  
          category:'Around The House',
          number_of_words: 3,
          total_number_of_letters: 17,
          first_word: 5,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Plaid Flannel Shirt',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 3,
          total_number_of_letters: 21,
          first_word: 8,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Sardines And Tangerines',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 3,
          total_number_of_letters: 12,
          first_word: 4,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Meet And Greet',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 3,
          total_number_of_letters: 11,
          first_word: 2,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'In Like Flynn',
        },{  
          category:'Rhyme Time',
          number_of_words: 3,
          total_number_of_letters: 11,
          first_word: 5,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Claim To Fame',
        }
      ]
    },
    four_word_answers: {
      date: 'Oct 07 2018',
      puzzle_bank: [
        {  
          category: 'Around The House',
          number_of_words: 4,
          total_number_of_letters: 17,
          first_word: 4, 
          description:'Location or object(s) found within a typical house.',
          correct_answer: 'Roll Of Toilet Paper',
        },
        {  
          category: 'The 90s',
          number_of_words: 4,
          total_number_of_letters: 14,
          first_word: 5, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Saved By The Bell',
        },
        {  
          category: 'The 90s',
          number_of_words: 4,
          total_number_of_letters: 18,
          first_word: 3, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'The Mickey Mouse Club',
        },
        {  
          category: 'Around The House',
          number_of_words: 1,
          total_number_of_letters: 17,
          first_word: 4,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Vase Full Of Flowers',
        },
        {  
          category: 'The 90s',
          number_of_words: 4,
          total_number_of_letters: 24,
          first_word: 6, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'There\'s Something About Mary',
        },
        {  
          category: 'Around The House',
          number_of_words: 4,
          total_number_of_letters: 21,
          first_word: 4,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'High Thread Count Sheets',
        },
        {  
          category: 'The 90s',
          number_of_words: 4,
          total_number_of_letters: 18,
          first_word: 3, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Red Hot Chili Peppers',
        },
        {  
          category: 'Around The House',
          number_of_words: 4,
          total_number_of_letters: 22,
          first_word: 5,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Fancy White Cloth Napkins',
        },
        {  
          category: 'Phrase',
          number_of_words: 4,
          total_number_of_letters: 8,
          first_word: 4, 
          description: 'any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'From A To Z',
        },
          {  
          category: 'The 90s',
          number_of_words: 4,
          total_number_of_letters: 22,
          first_word: 3, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Six Degrees of Separation',
        },
          {  
          category: 'The 90s',
          number_of_words: 4,
          total_number_of_letters: 19,
          first_word: 4, 
          description:'Puzzles pertaining to the decade in question.',
          correct_answer: 'Mary Kate & Ashley Olsen',
        },
        {  
          category: 'Phrase',
          number_of_words: 4,
          total_number_of_letters: 9,
          first_word: 3, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Sly As A Fox',
        },
        {  
          category: 'Phrase',
          number_of_words: 4,
          total_number_of_letters: 10,
          first_word: 3, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Pay As You Go',
        },
        {  
          category: 'Phrase',
          number_of_words: 4,
          total_number_of_letters: 11,
          first_word: 4, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Give Me A Hint',
        },
        {  
          category: 'Phrase',
          number_of_words: 4,
          total_number_of_letters: 12,
          first_word: 1, 
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'A Piece Of Cake',
        },
        {  
          category: 'Phrase',
          number_of_words: 4,
          total_number_of_letters: 12,
          first_word: 5,
          description: 'Any two (or more) related phrases separated by a comma or otherwise used consecutively',
          correct_answer: 'Happy As A Clam',
        },{  
          category: 'Around The House',
          number_of_words: 4,
          total_number_of_letters: 25,
          first_word: 5,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'Clear Plastic Shower Curtain',
        },{  
          category:'Rhyme Time',
          number_of_words: 4,
          total_number_of_letters: 10,
          first_word: 4,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Snug As A Bug',
        },{  
          category:'Rhyme Time',
          number_of_words: 4,
          total_number_of_letters: 15,
          first_word: 4,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Ants In Your Pants',
        },
        {  
          category:'Around The House',
          number_of_words: 4,
          total_number_of_letters: 12,
          first_word: 1,
          description: 'Location or object(s) found within a typical house.',
          correct_answer: 'A Pile Of Coats',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 4,
          total_number_of_letters: 18,
          first_word: 4,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Good Golly Miss Molly',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 4,
          total_number_of_letters: 21,
          first_word: 7,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'Hostess With The Mostest',
        },
        {  
          category:'Rhyme Time',
          number_of_words: 4,
          total_number_of_letters: 22,
          first_word: 2,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'An Attitude of Gratitude',
        },{  
          category:'Rhyme Time',
          number_of_words: 4,
          total_number_of_letters: 16,
          first_word: 3,
          description: 'Rhyming word(s) or phrase(s).',
          correct_answer: 'You Snooze You Lose',
        }
      ]
    }
  }
};